USB_VID = 0x303A
USB_PID = 0x00EB
USB_PRODUCT = "Booklab"
USB_MANUFACTURER = "Discoverling"

IDF_TARGET = esp32s2

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 40m
CIRCUITPY_ESP_FLASH_SIZE = 4MB
